version: '3.8'

services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    volumes:
      - .:/home/soriaruiz
      - /home/data/post:/home/soriaruiz/src/main/resources/posts
      - /home/data/eventos:/home/soriaruiz/src/main/resources/eventos
      - /home/data/form:/home/soriaruiz/form
      - /home/data/logs:/home/soriaruiz/logs
    restart: unless-stopped
    env_file:
      - .env