spring.application.name=portfolio
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

# Custom properties
blog.posts.directory=src/main/resources/posts
app.logs.directory=logs
spring.devtools.restart.additional-paths=src/main/resources/posts,/home/soriaruiz/form
# Enable Ant Path Matching for legacy pattern support (**/*.png)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Groq API Configuration
groq.api.key=${GROQ_API_KEY}
groq.model=${GROQ_SYSTEM_MODEL}
groq.system.prompt=${GROQ_SYSTEM_PROMPT}
